<?php
return array (
  0 => 
  array (
    'WCD\\AppController' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/AppController/AppController.php',
      'time' => 1636024710,
    ),
    'WCD\\GutenbergBlocks' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/GutenbergBlocks/GutenbergBlocks.php',
      'time' => 1636024707,
    ),
    'WCD\\PostTypes' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/PostTypes/PostTypes.php',
      'time' => 1636024704,
    ),
    'WCD\\RestAPI\\Media' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/RestApi/Media/Media.php',
      'time' => 1636024693,
    ),
    'WCD\\RestAPI' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/RestApi/RestApi.php',
      'time' => 1634049978,
    ),
    'WCD\\RestAPIItem' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/RestApi/Item/Item.php',
      'time' => 1636024690,
    ),
    'WCD\\RestAPI\\Sandbox' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/RestApi/sandbox/Sandbox.php',
      'time' => 1636024700,
    ),
    'WCD\\RestAPI\\Posts' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/RestApi/Posts/Posts.php',
      'time' => 1636024698,
    ),
    'WCD\\WPSiteConfig' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/SiteConfig/SiteConfig.php',
      'time' => 1663850447,
    ),
    'WCD\\User' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/User/User.php',
      'time' => 1636024681,
    ),
    'WCD\\Acf' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/acf/Acf.php',
      'time' => 1634049978,
    ),
    'WCD\\AcfService' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/acf/AcfService.php',
      'time' => 1634049978,
    ),
  ),
  1 => 
  array (
    'TimberArchives' => 284,
    'WP_CLI_Command' => 556,
    'Timber\\Integrations\\Timber_WP_CLI_Command' => 278,
    'WP_Site_Health' => 272,
    'acf_third_party' => 266,
    'WooCommerce' => 74,
    'Tabify_Edit_Screen' => 263,
    'Post_Type_Switcher' => 260,
    'Dark_Mode' => 257,
    'acf_field_text' => 254,
    'acf_field_textarea' => 251,
    'acf_field_number' => 248,
    'acf_field_range' => 245,
    'acf_field_email' => 242,
    'acf_field_url' => 239,
    'acf_field_password' => 236,
    'acf_field_image' => 233,
    'acf_field_file' => 230,
    'acf_field_wysiwyg' => 227,
    'acf_field_oembed' => 224,
    'acf_field_select' => 221,
    'acf_field_checkbox' => 218,
    'acf_field_radio' => 215,
    'acf_field_button_group' => 212,
    'acf_field_true_false' => 209,
    'acf_field_link' => 206,
    'acf_field_post_object' => 203,
    'acf_field_page_link' => 200,
    'acf_field_relationship' => 197,
    'acf_field_taxonomy' => 194,
    'ACF_Field_User' => 191,
    'acf_field_google_map' => 188,
    'acf_field_date_picker' => 185,
    'acf_field_date_and_time_picker' => 182,
    'acf_field_time_picker' => 179,
    'acf_field_color_picker' => 176,
    'acf_field_message' => 173,
    'acf_field__accordion' => 170,
    'acf_field_tab' => 167,
    'acf_field__group' => 164,
    'acf_field_repeater' => 161,
    'acf_field_flexible_content' => 158,
    'acf_field_gallery' => 155,
    'acf_field_clone' => 152,
    'ACF_Location_Post_Type' => 149,
    'ACF_Location_Post_Template' => 146,
    'ACF_Location_Post_Status' => 143,
    'ACF_Location_Post_Format' => 140,
    'ACF_Location_Post_Category' => 137,
    'ACF_Location_Post_Taxonomy' => 134,
    'ACF_Location_Post' => 131,
    'ACF_Location_Page_Template' => 128,
    'ACF_Location_Page_Type' => 125,
    'ACF_Location_Page_Parent' => 122,
    'ACF_Location_Page' => 119,
    'ACF_Location_Current_User' => 116,
    'ACF_Location_Current_User_Role' => 113,
    'ACF_Location_User_Form' => 110,
    'ACF_Location_User_Role' => 107,
    'ACF_Location_Taxonomy' => 104,
    'ACF_Location_Attachment' => 101,
    'ACF_Location_Comment' => 98,
    'ACF_Location_Widget' => 95,
    'ACF_Location_Nav_Menu' => 92,
    'ACF_Location_Nav_Menu_Item' => 89,
    'ACF_Location_Block' => 86,
    'ACF_Location_Options_Page' => 83,
    'CoAuthors_Plus' => 65,
    'WP_Filesystem_direct' => 9,
    'ReallySimpleCaptcha' => 3,
    'WP_Automatic_Updater' => 11,
    'ACF' => 3,
    'phpQuery' => 6,
    'Mfn_Builder_Front' => 3,
    'WP_Optimize' => 4,
    'Updraft_Notices_1_2' => 7,
    'MatthiasMullie\\Minify\\Minify' => 4,
    'comet_cache' => 8,
    'zencache' => 5,
    'CMB2_Boxes' => 10,
    'Vc_Manager' => 3,
    'CMB2_Utils' => 7,
    'CMB2_Hookup' => 4,
    'CMB2_Hookup_Base' => 1,
    'WPCF7_Contact_Form_List_Table' => 1,
    'cmcmuxcss_GeneHelper' => 1,
    'WpeCommon' => 9,
    'Kinsta\\Cache_Purge' => 6,
    'WpFormsLite_Compatible' => 3,
    'Hummingbird\\WP_Hummingbird' => 2,
    'WPMUDEV_Dashboard' => 66,
    'WPMU_Free_Notice' => 7,
    'WPMUDEV_Recommended_Plugins_Notice_Registered_Plugin' => 3,
    'SF_Product' => 2,
    'post' => 3,
    'Breeze_PurgeCache' => 2,
    'Minify_HTML' => 1,
    'WP_Optimize_Admin' => 1,
    'WP_Site_Health_Auto_Updates' => 3,
  ),
);
