<?php
return array (
  0 => 
  array (
    'WCD\\AppController' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/AppController/AppController.php',
      'time' => 1636024710,
    ),
    'WCD\\GutenbergBlocks' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/GutenbergBlocks/GutenbergBlocks.php',
      'time' => 1636024707,
    ),
    'WCD\\PostTypes' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/PostTypes/PostTypes.php',
      'time' => 1636024704,
    ),
    'WCD\\RestAPI\\Media' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/RestApi/Media/Media.php',
      'time' => 1636024693,
    ),
    'WCD\\RestAPI' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/RestApi/RestApi.php',
      'time' => 1634049978,
    ),
    'WCD\\RestAPIItem' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/RestApi/Item/Item.php',
      'time' => 1636024690,
    ),
    'WCD\\RestAPI\\Sandbox' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/RestApi/sandbox/Sandbox.php',
      'time' => 1636024700,
    ),
    'WCD\\RestAPI\\Posts' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/RestApi/Posts/Posts.php',
      'time' => 1636024698,
    ),
    'WCD\\WPSiteConfig' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/SiteConfig/SiteConfig.php',
      'time' => 1663850447,
    ),
    'WCD\\User' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/User/User.php',
      'time' => 1636024681,
    ),
    'WCD\\Acf' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/acf/Acf.php',
      'time' => 1634049978,
    ),
    'WCD\\AcfService' => 
    array (
      'file' => '/home/zhornik/domains/bumerang.vot.pl/public_html/wp-dominik/wp-content/themes/tradedoubter_pvn/app/acf/AcfService.php',
      'time' => 1634049978,
    ),
  ),
  1 => 
  array (
    'TimberArchives' => 286,
    'WP_CLI_Command' => 560,
    'Timber\\Integrations\\Timber_WP_CLI_Command' => 280,
    'WP_Site_Health' => 274,
    'acf_third_party' => 268,
    'WooCommerce' => 75,
    'Tabify_Edit_Screen' => 265,
    'Post_Type_Switcher' => 262,
    'Dark_Mode' => 259,
    'acf_field_text' => 256,
    'acf_field_textarea' => 253,
    'acf_field_number' => 250,
    'acf_field_range' => 247,
    'acf_field_email' => 244,
    'acf_field_url' => 241,
    'acf_field_password' => 238,
    'acf_field_image' => 235,
    'acf_field_file' => 232,
    'acf_field_wysiwyg' => 229,
    'acf_field_oembed' => 226,
    'acf_field_select' => 223,
    'acf_field_checkbox' => 220,
    'acf_field_radio' => 217,
    'acf_field_button_group' => 214,
    'acf_field_true_false' => 211,
    'acf_field_link' => 208,
    'acf_field_post_object' => 205,
    'acf_field_page_link' => 202,
    'acf_field_relationship' => 199,
    'acf_field_taxonomy' => 196,
    'ACF_Field_User' => 193,
    'acf_field_google_map' => 190,
    'acf_field_date_picker' => 187,
    'acf_field_date_and_time_picker' => 184,
    'acf_field_time_picker' => 181,
    'acf_field_color_picker' => 178,
    'acf_field_message' => 175,
    'acf_field__accordion' => 172,
    'acf_field_tab' => 169,
    'acf_field__group' => 166,
    'acf_field_repeater' => 163,
    'acf_field_flexible_content' => 160,
    'acf_field_gallery' => 157,
    'acf_field_clone' => 154,
    'ACF_Location_Post_Type' => 151,
    'ACF_Location_Post_Template' => 148,
    'ACF_Location_Post_Status' => 145,
    'ACF_Location_Post_Format' => 142,
    'ACF_Location_Post_Category' => 139,
    'ACF_Location_Post_Taxonomy' => 136,
    'ACF_Location_Post' => 133,
    'ACF_Location_Page_Template' => 130,
    'ACF_Location_Page_Type' => 127,
    'ACF_Location_Page_Parent' => 124,
    'ACF_Location_Page' => 121,
    'ACF_Location_Current_User' => 118,
    'ACF_Location_Current_User_Role' => 115,
    'ACF_Location_User_Form' => 112,
    'ACF_Location_User_Role' => 109,
    'ACF_Location_Taxonomy' => 106,
    'ACF_Location_Attachment' => 103,
    'ACF_Location_Comment' => 100,
    'ACF_Location_Widget' => 97,
    'ACF_Location_Nav_Menu' => 94,
    'ACF_Location_Nav_Menu_Item' => 91,
    'ACF_Location_Block' => 88,
    'ACF_Location_Options_Page' => 85,
    'CoAuthors_Plus' => 67,
    'WP_Filesystem_direct' => 9,
    'ReallySimpleCaptcha' => 3,
    'WP_Automatic_Updater' => 11,
    'ACF' => 3,
    'phpQuery' => 6,
    'Mfn_Builder_Front' => 3,
    'WP_Optimize' => 4,
    'Updraft_Notices_1_2' => 7,
    'MatthiasMullie\\Minify\\Minify' => 4,
    'comet_cache' => 8,
    'zencache' => 5,
    'CMB2_Boxes' => 10,
    'Vc_Manager' => 3,
    'CMB2_Utils' => 7,
    'CMB2_Hookup' => 4,
    'CMB2_Hookup_Base' => 1,
    'WPCF7_Contact_Form_List_Table' => 1,
    'cmcmuxcss_GeneHelper' => 1,
    'WpeCommon' => 9,
    'Kinsta\\Cache_Purge' => 6,
    'WpFormsLite_Compatible' => 3,
    'Hummingbird\\WP_Hummingbird' => 2,
    'WPMUDEV_Dashboard' => 66,
    'WPMU_Free_Notice' => 7,
    'WPMUDEV_Recommended_Plugins_Notice_Registered_Plugin' => 3,
    'SF_Product' => 2,
    'post' => 3,
    'Breeze_PurgeCache' => 2,
    'Minify_HTML' => 1,
    'WP_Optimize_Admin' => 1,
    'WP_Site_Health_Auto_Updates' => 3,
    'WP_Debug_Data' => 2,
  ),
);
